using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Octokit;
using System.ComponentModel;
using System.Windows;

namespace CodeConnect.Gistify.Extension.ThirdParties
{
    static class GitHubIntegration
    {
        public static void HandleAugmentedSnippet(string snippet)
        {
            Task.Run(async  () =>
            {
                var gistUrl = await createGistAsync(snippet);
                if (Options.SavedOptions.Instance.AfterUploadValue.HasFlag(Options.SavedOptions.AfterUpload.LaunchBrowser))
                {
                    goToGist(gistUrl);
                }
                if (Options.SavedOptions.Instance.AfterUploadValue.HasFlag(Options.SavedOptions.AfterUpload.CopyLink))
                {
                    Clipboard.SetText(gistUrl);
                }
            });
            
        }

        private static void goToGist(string url)
        {
            if (String.IsNullOrWhiteSpace(url))
            {
                StatusBar.ShowStatus($"No link provided");
                return;
            }
            try
            {
                System.Diagnostics.Process.Start(url);
                StatusBar.ShowStatus($"Gist saved in {url}");
            }
            catch (Win32Exception noBrowser)
            {
                if (noBrowser.ErrorCode == -2147467259)
                {
                    StatusBar.ShowStatus($"Unable to open a web browser.");
                }
#if DEBUG
                System.Diagnostics.Debugger.Break();
#endif
            }
            catch
            {
                StatusBar.ShowStatus($"Gistify ran into an error.");
#if DEBUG
                System.Diagnostics.Debugger.Break();
#endif
            }
        }

        private static async Task<string> createGistAsync(string snippet)
        {
            try
            {
                var token = Options.SavedOptions.Instance.TokenValue;
                if (String.IsNullOrWhiteSpace(token))
                {
                    StatusBar.ShowStatus("Please provide GitHub access token in Tools > Options > Gistify");
                    return String.Empty;
                }
                var credentials = new Octokit.Credentials(token);

                var connection = new Connection(new ProductHeaderValue("Whatever"))
                {
                    Credentials = credentials
                };
                var github = new GitHubClient(connection);
                var newGist = new NewGist()
                {
                    Description = "Generated by Code Connect's Gistify",
                    Public = false,
                };
                newGist.Files.Add("fragment.cs", snippet);
                var gist = await github.Gist.Create(newGist).ConfigureAwait(false);
                return gist.HtmlUrl;
            }
            catch (Exception)
            {
                StatusBar.ShowStatus("Gistify ran into a problem creating the gist.");
                return String.Empty;
            }
        }
    }
}
